<?php
namespace Mett\CiteProc;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-30 at 16:32:33.
 */
class CiteProcTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var CiteProc
     */
    protected $object;

    /**
     * @var array
     */
    protected $publications;
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $file = file_get_contents(__DIR__."/data.json");

        $this->publications = json_decode($file);
    }

    /**
     * @group setup
     */
    public function testBasicInstanciation()
    {
        $config   = ['stylePath' => __DIR__ . '/data/styles/'];
        $csl      = (new ResourceLoader())->loadStyle('biological-reviews', $config);
        $citeProc = new CiteProc($csl, 'en-US');

        // basic test
        $this->assertTrue(is_object($citeProc));
    }

    /**
     * @group integration
     */
    public function testStyleAuthors()
    {
        $config   = ['stylePath' => __DIR__ . '/data/styles/'];
        $csl      = (new ResourceLoader())->loadStyle('apa', $config);
        $citeProc = new CiteProc($csl, 'en-US');

        // test if author from apa is correctly parsed
        $this->assertEquals([
            'name'  => 'Simon Kornblith',
            'email' => 'simon@simonster.com'
        ], $citeProc->info->authors[0]);
    }

    /**
     * @group integration
     */
    public function testStyleContributor()
    {
        $config   = ['stylePath' => __DIR__ . '/data/styles/'];
        $csl      = (new ResourceLoader())->loadStyle('apa', $config);
        $citeProc = new CiteProc($csl, 'en-US');

        // test if author from apa is correctly parsed
        $this->assertEquals([
            'name'  => 'Richard Karnesky',
            'email' => 'karnesky+zotero@gmail.com',
            'uri'   => 'http://arc.nucapt.northwestern.edu/Richard_Karnesky'
        ], $citeProc->info->contributor[2]);
    }

    /**
     * @group integration
     */
    public function testBasicCitation()
    {
        $config   = ['stylePath' => __DIR__ . '/data/styles/'];
        $csl      = (new ResourceLoader())->loadStyle('apa', $config);
        $citeProc = new CiteProc($csl, 'en-US');


        // test if author from apa is correctly parsed
        $this->assertEquals([
            'name'  => 'Richard Karnesky',
            'email' => 'karnesky+zotero@gmail.com',
            'uri'   => 'http://arc.nucapt.northwestern.edu/Richard_Karnesky'
        ], $citeProc->info->contributor[2]);
    }


    /**
     * @covers Mett\CiteProcessor\CiteProc::render
     * @group integration
     *
     * @todo   Implement testRender().
     */
    public function testRender()
    {
        foreach($this->publications as $key => $dataObject) {
            foreach($dataObject->rendereddata as $styleName => $renderedText) {
                $config   = ['stylePath' => __DIR__ . '/data/styles/'];
                $csl      = (new ResourceLoader())->loadStyle($styleName, $config);
                $lang     = substr($this->publications->{$key}->locales, 0, 2);
                $citeProc = new CiteProc($csl, $lang);
                $actual   = preg_replace("!(\s{2,})!", " ", strip_tags($citeProc->render($dataObject->rawdata)));

                $this->assertSame($renderedText, $actual, "Testing $key");
            }
        }
    }
}
